#!/usr/bin/env python

# WordCountJournal
# Copyright 2013 Hal Canary
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import datetime
import os
import PyQt4.QtGui
import PyQt4.QtCore

Location = os.path.join(os.path.expanduser("~"),'Documents','Journal')

class Journal(PyQt4.QtGui.QMainWindow):
	def __init__(self, parent=None):
		super(Journal, self).__init__(parent)
		self.setWindowTitle('WordCountJournal')
		today = datetime.date.today()
		year = today.year
		jdir = os.path.join(Location, str(year))
		try:
			os.makedirs(jdir)
		except (OSError,):
			pass # directory already exists
		self.jfile = os.path.join(jdir, 'journal-%s.txt' % today.isoformat())

		self.textEdit = PyQt4.QtGui.QTextEdit(self)
		self.statusBar =PyQt4.QtGui.QStatusBar()

		try:
			with open(self.jfile, 'rU') as f:
				self.textEdit.setPlainText(f.read())
		except (IOError,):
			pass # file does not exist
		self.textHasChanged()

		self.textEdit.connect(
			self.textEdit,PyQt4.QtCore.SIGNAL("textChanged()"),
			self.textHasChanged)
		ctrlq = PyQt4.QtGui.QAction(self)
		self.addAction(ctrlq)
		ctrlq.setShortcut('Ctrl+Q')
		ctrlq.connect(ctrlq, PyQt4.QtCore.SIGNAL("triggered()"), self.close)
		self.resize(500, 500)
		self.setCentralWidget(self.textEdit)
		self.setStatusBar(self.statusBar)

	def textHasChanged(self):
		v = str(self.textEdit.toPlainText())
		s = sum(len(l.split()) for l in v.split('\n'))
		self.statusBar.showMessage ("Word Count: %s" % s)

	def closeEvent(self, event):
		v = str(self.textEdit.toPlainText())
		if len(v) > 0 and v[-1] != '\n':
			v = v + '\n'
		with open(self.jfile,'w') as f:
			f.write(v)

app = PyQt4.QtGui.QApplication([])
journal = Journal()
journal.show()
app.exec_()
